# 서비스 설정 - 외부에 노출하기 위한 목적
apiVersion: v1
kind: Service
metadata:
  name: mysql # DNS Name
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None